### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by gerald-brandt** [yhirose/cpp-unicodelib#2]
With the use of char32_t and U32string (const char32_t *), am I to believe this library uses UTF32 throughout, and if I do everything in UTF8, I'll have to convert to and from UTF32 every time I call a library function?

**Comment by yhirose** [comment]
@gerald-brandt, yes, you are correct. All the functions are written based on UTF32. So, users need to convert UTF8 text to UTF32 first.

That's my design decision. Unicode spec and UAX are based on codepoint or Unicode scalar. So it was easier for me to use `char32_t` to translate the algorithms in the spec to C++ code. Of course, some simple functions like Unicode Property can be written on UTF8. But more complex ones like Text Segmentation is hard to be written based on UTF8. For consistency, I used `char32_t` though out my code.

Hope it helps!

**Comment by gerald-brandt** [comment]
Perfect, thanks!
