### ISSUE TITLE
UB in conversion functions

### ISSUE THREAD

**Issue by sfpvk** [yhirose/cpp-unicodelib#3]
Good project.

I think there is Undefined Behavior in wstring conversions functions. For example
```
inline std::wstring to_wstring_core(const char *s8, size_t l) {
...
    return std::wstring(reinterpret_cast<const wchar_t *>(s16.data()),
                        s16.length());
...
}
```
I think this reinterpret_cast is UB. But it can be easily fixed in all cases where reinterpret_cast is used:
```
    return std::wstring(reinterpret_cast<const wchar_t *>(s16.begin(), s16.end());
```

**Comment by yhirose** [comment]
Your suggested code cannot be compiled...

**Comment by sfpvk** [comment]
In attachment is a patch which fixes the problem. You can apply it with ```$ git apply encodings_UB.txt```

[encodings_UB.txt](https://github.com/yhirose/cpp-unicodelib/files/8375440/encodings_UB.txt)
